server {
    listen 80;
    server_name vpn-ger.kolibrisquad.ru;

    root /usr/share/nginx/html;
    index index.html;

    # Отдача статики и поддержка React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Проксирование запросов на Spring Boot бэкенд
    location /api/ {
        # 'backend' — это имя сервиса из docker-compose
        proxy_pass http://127.0.0.1:8080;        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}