services:
  backend:
    build:
      context: ./backend
    container_name: invitation-backend
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"

  frontend:
    build:
      context: ./frontend
    container_name: invitation-frontend
    restart: unless-stopped
    depends_on:
      - backend
    network_mode: "host"