services:
  backend:
    build:
      context: ./backend
    container_name: invitation-backend
    restart: always
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: invitation-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge